### ISSUE TITLE
run flutter project with erros

### ISSUE THREAD

**Issue by huixisheng** [dart-lang/dartdoc#2000] opened 2019-08-10 17:22 UTC
```
parsing /Users/huixisheng/.pub-cache/hosted/pub.flutter-io.cn/matcher-0.12.5/lib/mirror_matchers.dart...
  error: tool execution failed: Tool "sample" returned non-zero exit code (254) when run as "/usr/local/Cellar/dart/2.4.1/libexec/bin/dart /var/folders/h9/53v387jx0mq2rrywyyjfzs1h0000gn/T/dartdoc_snapshot_cache_uHg19Y/snapshot_0 --type=sample" from Directory: '/Users/huixisheng/Coding/Baiying/telephone-assistant-native'
Input to sample was:

This example shows usage of several OpenType font features, including
Small Caps (smcp), old-style figures, fractional ligatures and stylistic
sets.

```dart
class TypePage extends StatelessWidget {
 // The Cardo, Milonga and Raleway Dots fonts can be downloaded from
 // Google Fonts (https://www.google.com/fonts).

 final titleStyle = TextStyle(
   fontSize: 18,
   fontFeatures: [FontFeature.enable('smcp')],
   color: Colors.blueGrey[600],
 );

 @override
 Widget build(BuildContext context) {
   return Scaffold(
     body: Center(
       child: Column(
         mainAxisAlignment: MainAxisAlignment.center,
         children: <Widget>[
           Spacer(flex: 5),
           Text('regular numbers have their place:', style: titleStyle),
           Text('The 1972 cup final was a 1-1 draw.',
               style: TextStyle(
                 fontFamily: 'Cardo',
                 fontSize: 24,
               )),
           Spacer(),
           Text('but old-style figures blend well with lower case:',
               style: titleStyle),
           Text('The 1972 cup final was a 1-1 draw.',
               style: TextStyle(
                   fontFamily: 'Cardo',
                   fontSize: 24,
                   fontFeatures: [FontFeature.oldstyleFigures()])),
           Spacer(),
           Divider(),
           Spacer(),
           Text('fractions look better with a custom ligature:',
               style: titleStyle),
           Text('Add 1/2 tsp of flour and stir.',
               style: TextStyle(
                   fontFamily: 'Milonga',
                   fontSize: 24,
                   fontFeatures: [FontFeature.enable('frac')])),
           Spacer(),
           Divider(),
           Spacer(),
           Text('multiple stylistic sets in one font:', style: titleStyle),
           Text('Raleway Dots',
               style: TextStyle(fontFamily: 'Raleway Dots', fontSize: 48)),
           Text('Raleway Dots',
               style: TextStyle(
                 fontFeatures: [FontFeature.stylisticSet(1)],
                 fontFamily: 'Raleway Dots',
                 fontSize: 48,
               )),
           Spacer(flex: 5),
         ],
       ),
     ),
   );
 }
}
```
Stderr output was:
Error: Error when reading 'file:///var/folders/h9/53v387jx0mq2rrywyyjfzs1h0000gn/T/dartdoc_snapshot_cache_uHg19Y/snapshot_0': No such file or directory

, from dart-ui.FontFeature: (file:///Users/huixisheng/Env/flutter/bin/cache/pkg/sky_engine/lib/ui/text.dart:177:7)
^C
```

**Comment by keertip** [comment] 2019-08-12 17:37
@huixisheng , can you post instructions on how to reproduce the error?

**Comment by jpeiffer** [comment] 2019-08-13 23:25
I received the exact same error.  It only happened after upgrading to the latest `beta` version of Flutter.

```
~$ flutter doctor -v
[✓] Flutter (Channel beta, v1.8.3, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.8.3 at /Users/jpeiffer/flutter
    • Framework revision e4ebcdf6f4 (2 weeks ago), 2019-07-27 11:48:24 -0700
    • Engine revision 38ac5f30a7
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 0ca1582afd)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jpeiffer/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/jpeiffer/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.37.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (3 available)
    • Android SDK built for x86 64 • emulator-5554                        • android-x64 • Android 9 (API 28) (emulator)
    • iPhone Xʀ                    • 3CAD74E1-00AC-4869-A458-848713528BBA • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-4
      (simulator)
    • iPad Pro (10.5-inch)         • 32F6830D-2316-4D93-8A6D-50242ACC14B5 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-4
      (simulator)

• No issues found!
```

```
$ dartdoc --version
dartdoc version: 0.28.2
```

```
$ dart --version
Dart VM version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "macos_x64"
```

I received the error when I run:
```
$ dartdoc
```

This had been successfully working on my CI/CD server since Flutter `1.0.0`.

**Comment by jpeiffer** [comment] 2019-08-13 23:35
It looks like there a tool named `sample` may have been accidentally included in the `dartdoc` tool set (either from Dart for Flutter itself; I'm not sure).

I found that this command fixed the issue for me:
```
dartdoc --no-allow-tools
```

**Comment by keertip** [comment] 2019-08-14 06:02
@jpeiffer, thanks for the instructions to repo, was able to do so with dartdoc version: 0.28.2. Just to confirm, could you run `which dartdoc` and paste the output.

**Comment by keertip** [comment] 2019-08-14 06:15
Appears to be an issue with `dartdoc 0.28.2`. Testing on the master channel for flutter

```
[✓] Flutter (Channel master, v1.5.3-pre.1377, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.5.3-pre.1377 at /Users/keertip/src/flutter_src/flutter
    • Framework revision 5f637f434e (2 hours ago), 2019-08-14 00:39:36 -0400
    • Engine revision fec1c92f8f
    • Dart version 2.5.0 (build 2.5.0-dev.2.0 88c43bbcc4)
```

`dartdoc version: 0.28.4` I don't see the error.

**Comment by keertip** [comment] 2019-08-15 19:29
This has been fixed in flutter master and has to roll through to the other channels. Closing as there is no work to be done here.

**Comment by LeandroMoura3** [comment] 2019-12-05 20:40
I Have this error too.

In my project, the --no-allow-tools don't work.

**Comment by jcollins-g** [comment] 2019-12-05 20:57
Hi @LeandroMoura3 , can you indicate what version of dartdoc you are using?

**Comment by LeandroMoura3** [comment] 2019-12-06 13:51
Sorry for don't put it before.

Here is the version: dartdoc version: 0.28.2

My flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [versÃ£o 10.0.17763.864], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.40.2)
[√] Connected device (1 available)

• No issues found!

I get the dartdoc with the code:
pub global activate dartdoc

**Comment by LeandroMoura3** [comment] 2019-12-06 14:30
When I tried install dartdoc in pubspec with the newer version, I get this error:
Running "flutter pub get" in big_express_app...                 
The current Dart SDK version is 2.5.0.



Because big_express_app depends on dartdoc >=0.29.2 which requires SDK version >=2.6.0 <3.0.0, version solving failed.
pub get failed (1)
Process finished with exit code 1

**Comment by LeandroMoura3** [comment] 2019-12-06 14:55
I tried the follow command, and works:
flutter packages pub run dartdoc

I think that it run the higier version that runs in my flutter 2.5.0

When I make the follow command: 
flutter packages pub run dartdoc --version
I recive the follow answer: dartdoc version: 0.28.8

Thank you for your help.

**Comment by jcollins-g** [comment] 2019-12-06 15:39
Hi @LeandroMoura3, it looks like to get the fix you would need to be on a different channel for flutter.

**Closed by jcollins-g** 2019-12-06 15:39 UTC
