### ISSUE TITLE
Search should allow fully qualified name

### ISSUE THREAD

**Issue by floitschG** [dart-lang/dartdoc#916] opened 2015-09-22 13:42 UTC
On api.dartlang.org I currently can't search for "List.add". I have to search for "add" and then select the right one from the drop-down.

**Comment by sethladd** [comment] 2015-09-22 13:43
Agreed!  Dupe of https://github.com/dart-lang/dartdoc/issues/837

**Closed by sethladd** 2015-09-22 13:43 UTC

**Comment by floitschG** [comment] 2015-09-22 13:45
Sorry. Went through all open bugs, but missed that one...

**Comment by sethladd** [comment] 2015-09-22 13:46
No problem! We'll take care of dupes if we know about them. Just happy we get feedback!
