### ISSUE TITLE
link to `dart:` libaries

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#1011] opened 2015-11-02 05:45 UTC
Link to `dart:` libraries when they're referenced in the generated docs (using the https://api.dartlang.org address).

**Comment by sethladd** [comment] 2015-11-02 16:01
Classes? methods? Just the libraries?

**Comment by devoncarew** [comment] 2015-11-02 17:24
Classes and methods, in the same places we'd link to classes and methods from the package we're generating docs for.

**Comment by keertip** [comment] 2015-12-07 17:09
dupe of #739

**Closed by keertip** 2015-12-07 17:09 UTC
