### ISSUE TITLE
UnmodifiableListView extends class that is not part of Dart API

### ISSUE THREAD

**Issue by floitschG** [dart-lang/dartdoc#1481] opened 2017-08-11 09:16 UTC
_From @sgrekhov on June 21, 2016 10:45_

Please see https://api.dartlang.org/stable/1.16.0/dart-collection/UnmodifiableListView-class.html

> Inheritance Object ListBase<E> UnmodifiableListBase<E> UnmodifiableListView

But `UnmodifiableListBase` is not part of the Dart API. This has several consequences
First, I think, `UnmodifiableListBase` shold be made internal `_UnmodifiableListBase`
Second, it shouldn't be shown in documentation. Otherwise documentation became wrong. For example, it shows `operator []=` as inherited (it is really inherited from `UnmodifiableListBase`, but documentation shows `operator []=` as inherited from `ListBase` (because `UnmodifiableListBase` is not part of the API and has no documentation)). But `operator []=` in `ListBase` sets the value while `operator []=` in `UnmodifiableListView` throws `UnsupportedError`

Documentation issue regarding showing of internal interfaces is dart-lang/dartdoc#1173

_Copied from original issue: dart-lang/sdk#26736_

**Comment by floitschG** [comment] 2017-08-11 09:16
_From @lrhn on June 22, 2016 11:13_

This is similar to issue #26643 in that it exposes an interface from `dart:_internal`.

We can't make `UnmodifiableListBase` private because it's from a different library (`dart:_internal`).
We can either find a way to hide it from the DartDoc, move the class to `dart:collection` and make it private, or move it and keep it public.
The first option is still open (as an issue against the dartdoc tool), the second one is likely to fail because `UnmodifiableListBase` is also used in libraries other than `dart:collection`, so the third option looks better and better.

**Comment by jcollins-g** [comment] 2017-09-12 14:49
The @nodoc directive in dartdoc should permit you to hide a class from being documented.  However, the reason dartdoc thinks it is public is that it believes the symbol is exported from dart:collection.  That looks like a real bug.

**Comment by jcollins-g** [comment] 2017-10-02 17:12
This is a higher priority than #1173, because we are actually advertising things in the API that are not exported in some cases.

**Comment by jcollins-g** [comment] 2017-10-02 17:36
This bug is actually now just a straight duplicate of #1173.  The more serious elements of this were fixed in #1390 and related canonicalization fixes.

Compare current documentation: https://api.dartlang.org/dev/2.0.0-dev.2.0/dart-collection/UnmodifiableListView-class.html to the version first cited in the bug.  We still show operator[]= as inherited.  That's #1173.  However, the critical nature of this bug was that we were claiming it was inherited from ListBase.  That's no longer the case.  We actually just document this operator as inherited, without specifying anywhere else but UnmodifiableListView as where it comes from.

Fixing #1173 would mean lying about the inheritance status here if we inherit from a non-canonical class.

**Closed by jcollins-g** 2017-10-02 17:36 UTC
Labels: area-library, bug, library-core, P1
