### ISSUE TITLE
Can I include an external MD file in a dartdoc comment?

### ISSUE THREAD

**Issue by Luckey-Elijah** [dart-lang/dartdoc#2729] opened 2021-08-05 15:42 UTC
Given I have a library `accounts`. I want to include a markdown file (`accounts_doc.md`) in the dartdoc of the library docs.

Is there a way to complete this in dartdoc? Please see the syntax below for what I am trying to achieve.

##### `accounts.dart`
```dart
/// ## Accounts
/// Some comments.
/// {@include accounts_doc.md}
/// Some other comments.
library accounts;
```
##### `accounts_doc.md`
```md
### Docs from md file
This is the accounts documentation.
```

<details>
  <summary>What will be rendered:</summary>

  ## Accounts

  Some comments.

  ### Docs from md file

  This is the accounts documentation.

  Some other comments.
</details>

**Comment by jcollins-g** [comment] 2021-08-06 21:48
There is currently no way to do this in dartdoc.  It's an interesting idea and reasonable enough, though it will have implications in the larger toolchain should we implement it.

**Comment by Luckey-Elijah** [comment] 2021-08-06 22:29
Thanks for the response! Wasn't to sure if that was a feature/enhancement already

**Comment by srawlins** [comment] 2022-03-25 20:32
Duplicate of https://github.com/dart-lang/dartdoc/issues/1096.

**Closed by srawlins** 2022-03-25 20:32 UTC
Labels: enhancement, P3
