### ISSUE TITLE
Numerous duplicated libraries appear in MDL's docs

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1014] opened 2015-11-02 18:52 UTC
See https://www.dartdocs.org/documentation/mdl/1.8.1/

![screen shot 2015-11-02 at 10 51 27 am](https://cloud.githubusercontent.com/assets/5479/10890909/de1fe64a-814f-11e5-8026-e69a441707fa.png)

Notice that "main" is repeated over and over.

Here's the original source code: https://github.com/MikeMitterer/dart-material-design-lite

**Comment by sethladd** [comment] 2015-11-02 18:53
cc @MikeMitterer

**Comment by MikeMitterer** [comment] 2015-11-03 09:05
Hm - maybe because of the samples??? https://github.com/MikeMitterer/dart-material-design-lite/tree/master/samples

**Comment by keertip** [comment] 2015-11-05 23:42
@MikeMitterer , looks like the multiple `main`s are from the  files in `lib/_templates`. Guessing they are probably not part of the public api? You can use an --excludes to exclude them, or move them to `lib/src` and that way they will not be part of the public api.

**Comment by sethladd** [comment] 2015-11-06 00:39
Thanks for the analysis! So maybe this isn't a bug?

Perhaps there's a feature in here... ability to mark a library as "not for docs" ?

@keertip feel free to reclassify this issue.

**Comment by keertip** [comment] 2015-11-06 01:28
We have a feature request for the ability to mark an element as "not for docs"  

Dupe of #642

**Closed by keertip** 2015-11-06 01:28 UTC

**Comment by MikeMitterer** [comment] 2015-11-26 19:34
In the meantime I have moved the samples to another project
