### ISSUE TITLE
Bad state: Members must be created from a declarations

### ISSUE THREAD

**Issue by ValentinVignal** [dart-lang/dartdoc#3225] opened 2022-10-20 15:57 UTC
I have this small code snippet:

```dart
abstract class FirstClass<T> {
  FirstClass({
    required String value,
  });
}

abstract class SecondClass<T> extends FirstClass {
  SecondClass({
    required super.value,
  });
}

/// {@template third_class}
/// [UnknownClass].
/// {@endtemplate}
class ThirdClass extends SecondClass {
  /// {@macro third_class}
  ThirdClass({
    required super.value,
  });
}
```

which, I know, doesn't make much sense, but it is still a valid dart code.

When I run 

```
dart doc
```

I get an error: `failed: Bad state: Members must be created from a declarations.`

```
Documenting flutter_app_stable...
Initialized dartdoc with 25 libraries
Generating docs for library main from package:flutter_app_stable/main.dart...
  warning: unresolved doc reference [UnknownClass]
    from main.ThirdClass: (file:///Users/valentin/Perso/Projects/flutter_app_stable/lib/main.dart:16:7)
|
dartdoc 5.1.0-dev (/Users/valentin/Perso/Projects/flutter_app_stable/dartdev) failed: Bad state: Members must be created from a declarations.
#0      new Member (package:analyzer/src/dart/element/member.dart:460:7)
#1      new VariableMember (package:analyzer/src/dart/element/member.dart:1126:7)
#2      new _ParameterMember&VariableMember&ParameterElementMixin (package:analyzer/src/dart/element/member.dart)
#3      new ParameterMember._ (package:analyzer/src/dart/element/member.dart:828:7)
#4      new ParameterMember (package:analyzer/src/dart/element/member.dart:811:28)
#5      SuperFormalParameterMember.superConstructorParameter (package:analyzer/src/dart/element/member.dart:1054:12)
#6      Constructor.referenceChildren.<anonymous closure>.dereferenceParameter (package:dartdoc/src/model/constructor.dart:108:47)
#7      Constructor.referenceChildren.<anonymous closure>.dereferenceParameter (package:dartdoc/src/model/constructor.dart:108:16)
#8      Constructor.referenceChildren.<anonymous closure>.<anonymous closure> (package:dartdoc/src/model/constructor.dart:115:26)
#9      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#10     ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#11     Constructor.referenceChildren.<anonymous closure> (package:dartdoc/src/model/constructor.dart:121:27)
#12     Constructor.referenceChildren (package:dartdoc/src/model/constructor.dart:124:4)
#13     Constructor.referenceChildren (package:dartdoc/src/model/constructor.dart)
#14     CommentReferable.referenceBy (package:dartdoc/src/model/comment_referable.dart:115:38)
#15     _getMatchingLinkElementCommentReferable (package:dartdoc/src/markdown_processor.dart:225:31)
#16     getMatchingLinkElement (package:dartdoc/src/markdown_processor.dart:266:16)
#17     _makeLinkNode (package:dartdoc/src/markdown_processor.dart:233:16)
#18     new MarkdownDocument.withElementLinkResolver.linkResolver (package:dartdoc/src/markdown_processor.dart:340:14)
#19     LinkSyntax._resolveReferenceLink (package:markdown/src/inline_parser.dart:1057:34)
#20     LinkSyntax._tryCreateReferenceLink (package:markdown/src/inline_parser.dart:1085:12)
#21     LinkSyntax.close (package:markdown/src/inline_parser.dart:1028:12)
#22     InlineParser._linkOrImage (package:markdown/src/inline_parser.dart:152:29)
#23     InlineParser.parse (package:markdown/src/inline_parser.dart:108:9)
#24     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:383:67)
#25     MarkdownDocument._parseInlineContent (package:dartdoc/src/markdown_processor.dart:388:9)
#26     MarkdownDocument.parseMarkdownText (package:dartdoc/src/markdown_processor.dart:373:5)
#27     Documentation._parseDocumentation (package:dartdoc/src/model/documentation.dart:61:21)
#28     Documentation._renderDocumentation (package:dartdoc/src/model/documentation.dart:40:23)
#29     Documentation.asOneLiner (package:dartdoc/src/model/documentation.dart:32:7)
#30     ModelElement.oneLineDoc (package:dartdoc/src/model/model_element.dart:831:50)
#31     _deduplicated_lib_templates_html__constructors_html (package:dartdoc/src/generator/templates.aot_renderers_for_html.dart:3993:29)
#32     _renderClass_partial_constructors_9 (package:dartdoc/src/generator/templates.aot_renderers_for_html.dart:2367:5)
#33     renderClass (package:dartdoc/src/generator/templates.aot_renderers_for_html.dart:359:16)
#34     HtmlAotTemplates.renderClass (package:dartdoc/src/generator/templates.dart:129:30)
#35     DartdocGeneratorBackend.generateClass (package:dartdoc/src/generator/dartdoc_generator_backend.dart:137:29)
#36     GeneratorFrontEnd._generateDocs (package:dartdoc/src/generator/generator_frontend.dart:76:29)
#37     GeneratorFrontEnd.generate (package:dartdoc/src/generator/generator_frontend.dart:23:11)
#38     Dartdoc.generateDocsBase (package:dartdoc/src/dartdoc.dart:181:21)
<asynchronous suspension>
#39     Dartdoc.generateDocs (package:dartdoc/src/dartdoc.dart:223:24)
<asynchronous suspension>
#40     Dartdoc.executeGuarded.<anonymous closure> (package:dartdoc/src/dartdoc.dart:261:9)
<asynchronous suspension>
```

This is the minimal code I could create to reproduce the issue.

If I do one of those changes:
- Remove the documentation on the `ThirdClass` constructor
- Remove the `<T>` of the `SecondClass` 
- Remove `value` parameter from the `FirstClass` constructor
- Remove the `SecondClass` and make `ThirdClass` extend `FirstClass`
- Remove the `[UnkownClass]` in the template of the `ThirdClass`

I don't have the issue anymore.

**Comment by jcollins-g** [comment] 2023-04-25 17:09
I am unable to reproduce this issue at head, so closing for now.

**Closed by jcollins-g** 2023-04-25 17:09 UTC
Labels: bug, P1
