### ISSUE TITLE
Dartdoc 8.3.1 broken for sass_api package

### ISSUE THREAD

**Issue by nex3** [dart-lang/dartdoc#3948] opened 2024-12-18 23:50 UTC
See https://github.com/sass/dart-sass/actions/runs/12379567472/job/34554002854?pr=2459:

```
dartdoc 8.3.1 (/home/runner/work/dart-sass/dart-sass/pkg/sass_api/.dart_tool/pub/bin/dartdoc/dartdoc.dart-3.6.0.snapshot) failed: LateInitializationError: Field 'objectClass' has not been initialized.
#0      PackageGraph.objectClass (package:dartdoc/src/model/package_graph.dart)
#1      Mixin.superclassConstraints.<anonymous closure> (package:dartdoc/src/model/mixin.dart:22:54)
#2      WhereIterator.moveNext (dart:_internal/iterable.dart:461:13)
#3      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#4      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#5      new List.of (dart:core-patch/array_patch.dart:3[9](https://github.com/sass/dart-sass/actions/runs/12379567472/job/34554002854?pr=2459#step:5:10):18)
#6      Mixin.superclassConstraints (package:dartdoc/src/model/mixin.dart:18:69)
#7      Mixin.superclassConstraints (package:dartdoc/src/model/mixin.dart)
#8      Mixin.inheritanceChain (package:dartdoc/src/model/mixin.dart:35:8)
#9      Mixin.inheritanceChain (package:dartdoc/src/model/mixin.dart)
#[10](https://github.com/sass/dart-sass/actions/runs/12379567472/job/34554002854?pr=2459#step:5:11)     InheritingContainer._inheritedElements.<anonymous closure> (package:dartdoc/src/model/inheriting_container.dart:157:9)
#[11](https://github.com/sass/dart-sass/actions/runs/12379567472/job/34554002854?pr=2459#step:5:12)     InheritingContainer._inheritedElements (package:dartdoc/src/model/inheriting_container.dart:196:4)
#[12](https://github.com/sass/dart-sass/actions/runs/12379567472/job/34554002854?pr=2459#step:5:13)     InheritingContainer._inheritedElements (package:dartdoc/src/model/inheriting_container.dart)
#[13](https://github.com/sass/dart-sass/actions/runs/12379567472/job/34554002854?pr=2459#step:5:14)     InheritingContainer.inheritedMethods (package:dartdoc/src/model/inheriting_container.dart:104:35)
#[14](https://github.com/sass/dart-sass/actions/runs/12379567472/job/34554002854?pr=2459#step:5:15)     InheritingContainer.instanceMethods (package:dartdoc/src/model/inheriting_container.dart:356:12)
#[15](https://github.com/sass/dart-sass/actions/runs/12379567472/job/34554002854?pr=2459#step:5:16)     Container.allModelElements (package:dartdoc/src/model/container.dart:59:12)
#[16](https://github.com/sass/dart-sass/actions/runs/12379567472/job/34554002854?pr=2459#step:5:17)     InheritingContainer._allModelElements (package:dartdoc/src/model/inheriting_container.dart:98:14)
#[17](https://github.com/sass/dart-sass/actions/runs/12379567472/job/34554002854?pr=2459#step:5:18)     InheritingContainer._allModelElements (package:dartdoc/src/model/inheriting_container.dart)
#[18](https://github.com/sass/dart-sass/actions/runs/12379567472/job/34554002854?pr=2459#step:5:19)     InheritingContainer.allModelElements (package:dartdoc/src/model/inheriting_container.dart:281:46)
#[19](https://github.com/sass/dart-sass/actions/runs/12379567472/job/34554002854?pr=2459#step:5:20)     Library.allModelElements (package:dartdoc/src/model/library.dart:444:32)
#20     Library.allModelElements (package:dartdoc/src/model/library.dart)
#21     PackageGraph._gatherModelElements (package:dartdoc/src/model/package_graph.dart:882:36)
#22     PackageGraph._precacheLocalDocs (package:dartdoc/src/model/package_graph.dart:160:28)
#23     PackageGraph.initializePackageGraph (package:dartdoc/src/model/package_graph.dart:126:11)
#24     PubPackageBuilder.buildPackageGraph (package:dartdoc/src/model/package_builder.dart:1[20](https://github.com/sass/dart-sass/actions/runs/12379567472/job/34554002854?pr=2459#step:5:21):22)
<asynchronous suspension>
#25     Dartdoc.generateDocsBase (package:dartdoc/src/dartdoc.dart:189:24)
<asynchronous suspension>
#26     Dartdoc.generateDocs (package:dartdoc/src/dartdoc.dart:241:24)
<asynchronous suspension>
#27     Dartdoc.executeGuarded.<anonymous closure> (package:dartdoc/src/dartdoc.dart:273:9)
<asynchronous suspension>
```

You can reproduce this on Dart 3.6.0 by running:

```
$ git clone https://github.com/sass/dart-sass
$ cd dart-sass/pkg/sass_api/
$ dart pub get
$ dart run dartdoc --quiet --no-generate-docs --errors ambiguous-doc-reference,broken-link,deprecated --errors unknown-directive,unknown-macro,unresolved-doc-reference
```

**Comment by srawlins** [comment] 2024-12-19 00:42
Thanks for filing an issue. This looks like a duplicate of https://github.com/dart-lang/dartdoc/issues/3947.

**Closed by srawlins** 2024-12-19 00:42 UTC
