### ISSUE TITLE
Double const

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1085] opened 2016-01-19 19:42 UTC
For example:

![screen shot 2016-01-15 at 10 10 32 am](https://cloud.githubusercontent.com/assets/5479/12429897/944a026e-bea1-11e5-899f-c301014bfedd.png)

Notice how it says "const const _IsAnything()"

We might not want to print "const" twice?

(found this in the docs for test)

**Comment by keertip** [comment] 2016-01-22 17:27
@sethladd , not sure how we would address this.  Take a look at the source
```
/// Returns a matcher that matches the isEmpty property.
const Matcher isEmpty = const _Empty();
```

So in the documentation, the first `const` is from dartdoc, the second is part  of the value assigned to that const. So it is not a bug on the part of dartdoc, it just that here the value of the const creates the situation of having two const's.

**Comment by sethladd** [comment] 2016-01-22 17:57
A couple of ideas.

A) remove _const_ and `const _Empty()`. Don't print anything in the third line. We already know it's a const (it's under a section called Constants) and we show the full value on the dedicated page anyway.

B) remove _const_, as it's redundant. All these names are under a section called Constants, and we show `const _Empty()` anyway.

I'm partial to option A.

Thoughts?

**Comment by keertip** [comment] 2016-01-22 18:23
will go with B). That way people can see the values on the main page, and go to the dedicated page if there is more to read.

**Comment by sethladd** [comment] 2016-01-22 18:26
great, thanks!

**Closed** 2016-01-25 04:56 UTC
Labels: bug
