### ISSUE TITLE
Flutter docs point to the wrong Point

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1195] opened 2016-07-11 19:49 UTC
The links in http://docs.flutter.io/flutter/dart-ui/Point-class.html target the Point class from dart:math rather than the dart_ui Point class. Likewise for the Canvas docs and (I would guess) other classes that refer to Point.

(From https://github.com/flutter/flutter/issues/4884)

**Comment by Hixie** [comment] 2016-07-11 21:27
Might be a dupe of https://github.com/dart-lang/dartdoc/issues/1160

**Closed** 2016-07-21 18:54 UTC
Labels: bug, customer-flutter, P1
