### ISSUE TITLE
provide a mechanism for constraining dartdoc output from angular2

### ISSUE THREAD

**Issue by naomiblack** [dart-lang/dartdoc#884] opened 2015-09-02 01:16 UTC
This is a problem that may be unique to Angular 2 -- we need a way to constrain what shows up in the dartdoc output. Because of the we are single-sourcing JS and Dart from our codebase, we end up with everything exported in the dartdoc output, including things that are really Angular 2 internals.

One way to solve this might be a manifest file that specifies structure from a multi-package dart project (e.g. we want angular2.bootstrap, angular2.router, angular2.di, etc... all available to the developer, but some of the classes in those libs should be hidden)

This is related to https://github.com/angular/ts2dart/issues/276. We need someone to pair with on the dartdoc side to understand which parts of the problem can be solved by dartdoc, and which need to be addressed in ts2dart.

**Comment by sethladd** [comment] 2015-09-02 16:18
Hi!

If you want to ignore certain libraries, you could try `--exclude` or `--include` to control what libraries are displayed.

If you need to hide certain _classes_, you could put an annotation on them and then tell dartdoc to ignore things with a certain annotation.

(note we don't do that last part today, but we could. We had another request for that.)

**Comment by keertip** [comment] 2015-09-18 20:45
@naomiblack , is this just suppressing docs for certain classes, or is there more to it?

**Comment by sethladd** [comment] 2015-10-06 16:19
Looks like a dupe of https://github.com/dart-lang/dartdoc/issues/642

**Closed by sethladd** 2015-10-06 16:19 UTC
Labels: needs_info
