### ISSUE TITLE
Move towards de-emphasizing library names and emphasizing paths under packages

### ISSUE THREAD

**Issue by natebosch** [dart-lang/dartdoc#2852] opened 2021-11-02 21:39 UTC
The discussion in https://github.com/dart-lang/language/issues/1941 highlighted a mismatch between how our tools think about libraries (the URI is the important thing - a library is identified by it's path under a package) vs how some users think about libraries (the library name is the important thing - a library is identified by a package and an opaque name).

The Dart doc UI currently highlights library names which may be reinforcing this. Most authors at this point don't concern themselves with the library name and DartDoc picks a default in many cases. This can lead to situations like having libraries that are indistinguishable without mousing over them.

![image](https://user-images.githubusercontent.com/7528195/139955288-e257c946-482a-4560-97a7-784396a53f2f.png)

These names also don't give any indication to users how they should import the libraries.

Can we replace the library names in these lists, with the path under `lib/`?

**Comment by jcollins-g** [comment] 2023-04-25 16:40
closing as duplicate of #1658

**Closed by jcollins-g** 2023-04-25 16:40 UTC
Labels: bug, P2
