### ISSUE TITLE
extension docs "on" line points to extension

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#2697] opened 2021-06-21 23:18 UTC
e.g. https://master-api.flutter.dev/flutter/flutter_test/TestBasicMessageChannelExtension.html

The "on" after the doc text points to the same page. I'm assuming it should say "on BasicMessageChannel" and point to that?

**Comment by lrhn** [comment] 2021-06-24 09:17
Came here to say the same thing; https://pub.dev/documentation/ffi/latest/ffi/StringUtf8Pointer.html

**Comment by jcollins-g** [comment] 2021-06-27 17:14
This looks like it is fixed in head, can only reproduce in the v0.45.0 tag.  My guess is @srawlins fixed a problem in template resolution as part of the AOT template work.

**Closed by jcollins-g** 2021-06-27 17:14 UTC
Labels: P1, bug
