### ISSUE TITLE
dartdoc should group extension method with the class being extended if they are in the same import

### ISSUE THREAD

**Issue by brianquinlan** [dart-lang/dartdoc#2854] opened 2021-11-11 20:01 UTC
Motivation:
1. I want to know more about `Future`s
2. I google for "Future dart"  and end up on the [`Future<T>` documentation page](https://api.dart.dev/stable/2.14.3/dart-async/Future-class.html)
3. I miss the existence of the `ignore` method because it is documented separately in the [`Extensions` section](https://api.dart.dev/stable/2.14.3/dart-async/FutureExtensions.html)

In this case, `ignore` is implemented as an extension method for compatibility reasons (adding a method to an existing class can break 3p code that `implements` that class) not because it is logically separate from the class.

Ideally, if the extension method is defined in the same package, it would be documented with the class or, at minimum, a link to the related extensions should be shown.

**Comment by srawlins** [comment] 2021-11-18 19:43
+1 this is a great idea.

**Comment by srawlins** [comment] 2022-03-25 20:34
Duplicate of https://github.com/dart-lang/dartdoc/issues/2021

**Closed by srawlins** 2022-03-25 20:34 UTC
