### ISSUE TITLE
Docs containing backslashes seem to get garbled

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#1364] opened 2017-04-02 07:23 UTC
Docs containing backslashes seem to get garbled. For example:
https://www.dartdocs.org/documentation/path/1.4.1/path/Style/windows.html
https://www.dartdocs.org/documentation/path/1.4.1/path/Style-class.html
```
Windows paths use "" (backslash) as separators. Absolute paths start with a drive letter followed by a colon (example, "C:") or two backslashes ("\") for UNC paths.
```

**Comment by jcollins-g** [comment] 2018-08-17 20:51
#1741 has a possible "fix" for some cases of this, but the real 'problem' is that markdown allows escaping and always assumes that a backslash is an intentional markdown escape.

It might be that we mark this WAI and tell everyone to use double backslashes to display literal ones, just like you do in markdown.

**Comment by jcollins-g** [comment] 2018-08-28 21:26
Going to close this "working as intended".  Either use double backslashes, or backquotes, to solve this problem as in dart-lang/path#45.

**Closed** 2018-08-29 18:38 UTC
Labels: P2, customer flutter
