### ISSUE TITLE
Show a list of all classes that _implement_ a class?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1069] opened 2015-12-20 19:37 UTC
Hi,

I'm trying to learn what Curves I have in Flutter. I'd love to see, when looking at Curve, what implements Curve. Is that possible?

Thanks!

http://docs.flutter.io/flutter/animation/Curve-class.html

![screen shot 2015-12-20 at 11 35 49 am](https://cloud.githubusercontent.com/assets/5479/11919674/faa5837c-a70d-11e5-9379-7fbd363d952b.png)

**Comment by sethladd** [comment] 2015-12-20 20:05
I think we are using 0.8.4

**Comment by Hixie** [comment] 2017-04-07 23:20
I'm bumping this up to P1 because I just saw this trip up a usability study participant (P3) and they really had no way to answer their question ("what inherits from Foo") without it.

**Comment by Hixie** [comment] 2017-04-07 23:22
Looks like this is a dupe of https://github.com/dart-lang/dartdoc/issues/1334.

**Closed by Hixie** 2017-04-07 23:22 UTC
Labels: customer flutter, enhancement, P1

**Comment by devoncarew** [comment] 2017-04-07 23:26
Just FYI, @jcollins-g has a PR out that fixes this issue (along with a number of others). It's a big PR, so will take a few days to land.
