### ISSUE TITLE
Provide a way to hide some doc comments from the dartdoc output

### ISSUE THREAD

**Issue by naomiblack** [dart-lang/dartdoc#941] opened 2015-10-06 01:29 UTC
In Angular, we use `@internal` annotation inside of the doc comments to identify doc sections that should be hidden from the published API docs. Specifically, we want to hide any text that appears after the `@internal` use in the doc comments.

Could dartdoc support this?

**Comment by yjbanov** [comment] 2015-10-06 16:16
Dart uses a flavor of markdown for doc comments. If it also understands markdown comments, we could simply convert those to comments.

**Comment by sethladd** [comment] 2015-10-06 16:19
Thanks for the request! Dupe of https://github.com/dart-lang/dartdoc/issues/642

**Comment by yjbanov** [comment] 2015-10-06 16:23
I don't think this is a dupe. The difference is:

#642 would like to support the following:

```dart
class Foo {
  @undocumented
  String someField;
}
```

#941 would like to support the following:

```dart
/**
 * This string appears in dartdoc output
 *
 * @internal this one doesn't
 */
class Foo {
}
```

**Comment by sethladd** [comment] 2015-10-06 16:24
Can we pick just one method? :)

**Comment by yjbanov** [comment] 2015-10-06 16:29
We could if the proposed two methods solved the same issue. #642 asks for an ability to pick a library member and exclude it from the docs (which is awesome! I want that too). This one's asking for an ability to make parts of the doc comment invisible. I think #941 can be solved by simply supporting markdown comments (after all Dart doc comments *are* markdown).

Can someone check if markdown comments `<!-- comment -->` are supported? (I am currently unable to run dartdoc for unknown reasons)

**Comment by sethladd** [comment] 2015-10-06 16:33
Oh, I see. Thanks for explaining. Yes, this is a new request. Thanks for reopening.

**Comment by keertip** [comment] 2015-10-07 15:53
@yjbanov , `<!-- comment -->` is not supported by the markdown package dartdoc uses, but

`[comment]: # (my comment )`

is supported and does not get shown in the generated docs. Would that work?

**Comment by yjbanov** [comment] 2015-10-07 17:07
That should work.  I'm not super clear on the syntax though. Which part is the comment itself, `my comment `, or `# (my comment )`, or something else?

**Comment by keertip** [comment] 2015-10-07 17:09
it is `my comment`. The rest of it `[comment]: # ()` is the necessary bits for markdown to ignore it.

**Comment by yjbanov** [comment] 2015-10-07 17:13
Great, thanks! We have two options then:

Given:

```dart
/**
 * This string appears in dartdoc output
 *
 * @internal this one doesn't
 */
class Foo {
}
```

## Option 1: use comment syntax

```dart
/**
 * This string appears in dartdoc output
 *
 * [comment]: # (@internal this one doesn't)
 */
class Foo {
}
```

## Option 2: move out of doc comment

```dart
/**
 * This string appears in dartdoc output
 */
//  @internal this one doesn't
class Foo {
}
```

**Closed by yjbanov** 2015-10-07 17:13 UTC
Labels: enhancement

**Comment by sethladd** [comment] 2015-10-07 19:58
Thanks for looking into this!
