### ISSUE TITLE
Change "Not documented" to "No description" for methods, properties, etc

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/dartdoc#1003] opened 2015-10-29 15:54 UTC
OLD description, obsoleted by #998:

----------------
When I looked at https://www.dartdocs.org/documentation/angular2/2.0.0-alpha.45/index.html, I saw "Library not documented" for every single library. At first I thought that there were no doc comments at all for that library, but https://www.dartdocs.org/documentation/angular2/2.0.0-alpha.45/angular2/angular2-library.html (at least) does have doc comments. (If I didn't know better, I might have thought that not even skeletal docs had been generated for the library.)

Please change "Library not documented" to "No description" or something else that makes clear that although the library has no description, something inside it might.

**Comment by kwalrath** [comment] 2015-10-29 15:57
Similarly, when you get down to the member level, I think "No description." would be clearer than "Not documented."

Example: https://www.dartdocs.org/documentation/angular2/2.0.0-alpha.45/angular2/DEFAULT_PIPES.html says "Not documented." I'd say that that page, even if it contains only information gleaned from code, is documentation!

**Comment by kwalrath** [comment] 2015-10-29 17:12
#998 is related.

**Comment by sethladd** [comment] 2015-10-29 17:14
I think we should just remove that message. Close as dupe of 998?

**Comment by kwalrath** [comment] 2015-10-29 17:20
Works for me, BUT be sure it's not just for libraries... for lower-level things, as well.

**Comment by sethladd** [comment] 2015-10-29 17:22
OK, let's split this issue into two. One for the library (988) and one for other places. OK to edit the title of this issue?

**Comment by kwalrath** [comment] 2015-10-29 17:25
Title edited. Or feel free to open a new issue.

**Closed** 2015-11-03 16:46 UTC
Labels: enhancement, user-feedback
