### ISSUE TITLE
links to old Dart docs not preserved

### ISSUE THREAD

**Issue by skybrian** [dart-lang/dartdoc#883] opened 2015-09-02 00:31 UTC
It looks like dartdoc isn't preserving any of the old links? For example, this link [1] just redirects to the top-level page. We should redirect them to the appropriate new page, because cool URI's don't change. [2]

[1] https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CB8QFjAAahUKEwjfi_rdi9fHAhXLPogKHVqECtU&url=https%3A%2F%2Fapi.dartlang.org%2Fapidocs%2Fchannels%2Fstable%2Fdartdoc-viewer%2Fdart%3Aconvert&usg=AFQjCNG8mW8SBCWh4g_m2Lte5UsZm9d-Dw&sig2=WgJbNcnnFJkLAnfGLXGdLQ

[2] http://www.w3.org/Provider/Style/URI.html

**Comment by sethladd** [comment] 2015-09-02 16:09
Dupe of https://github.com/dart-lang/api.dartlang.org/issues/45 ?

**Closed** 2015-09-02 16:09 UTC

**Comment by sethladd** [comment] 2015-09-02 22:24
FYI: CL to fix (known incorrect) redirects is https://codereview.chromium.org/1323233002/
