### ISSUE TITLE
Wrong signature for functions with typedeffed argument types

### ISSUE THREAD

**Issue by floitschG** [dart-lang/dartdoc#1163] opened 2016-05-23 16:57 UTC
Dartdoc generates a bad signature for functions that have an argument that is typed with a typedef.
For example: https://api.dartlang.org/stable/1.16.0/dart-html/EventTarget/addEventListener.html

It states that the `listener` should be a function that takes an `Event` and returns an `EventListener`:
`void addEventListener(String type, EventListener listener(Event event), [bool useCapture])`

However the actual signature is:
`void addEventListener(String type, EventListener listener, [bool useCapture]) {`

That is, the `listener` is an `EventListener` and not the `listener`'s return type.

**Comment by Hixie** [comment] 2016-06-16 19:34
this is a dupe of https://github.com/dart-lang/dartdoc/issues/1137

**Closed** 2016-06-16 22:14 UTC
