### ISSUE TITLE
Dartdoc crashes

### ISSUE THREAD

**Issue by ghost** [dart-lang/dartdoc#2678] opened 2021-06-11 00:47 UTC
For some reason, whenever I try to generate `dartdoc`, I get this following error:
```
Unhandled exception:
Invalid argument (uri): Unknown package: Instance of '_SimpleUri'
#0      ResourceLoader.resolveResourceUri.<anonymous closure> (package:dartdoc/src/generator/resource_loader.dart:41:11)
<asynchronous suspension>
#1      ResourceLoader.getResourceFile (package:dartdoc/src/generator/resource_loader.dart:31:15)
<asynchronous suspension>
#2      _DefaultTemplatesLoader.loadTemplate (package:dartdoc/src/generator/templates.dart:168:24)
<asynchronous suspension>
#3      Templates._create (package:dartdoc/src/generator/templates.dart:265:25)
<asynchronous suspension>
#4      initHtmlGenerator (package:dartdoc/src/generator/html_generator.dart:22:19)
<asynchronous suspension>
#5      Dartdoc.fromContext (package:dartdoc/dartdoc.dart:149:21)
<asynchronous suspension>
#6      main (file:///b/s/w/ir/cache/builder/src/third_party/dart/third_party/pkg/dartdoc/bin/dartdoc.dart:24:9)
<asynchronous suspension>
```

My computer information is below:

```
$ dartdoc --version
dartdoc version: 0.42.0
$ dart --version
Dart SDK version: 2.13.1 (stable) (Fri May 21 12:45:36 2021 +0200) on "linux_x64"
```

**Comment by srawlins** [comment] 2021-06-11 00:57
Are you generating dartdoc for an open source package? Can you give us the source and the commit on which you see this crash?

**Comment by Cutewarriorlover** [comment] 2021-06-11 01:37
I'm learning to make a transpiling programming language, it's the latest commit from https://gitea.com/Cutewarriorlover/lumos.

**Comment by Cutewarriorlover** [comment] 2021-06-11 01:49
I know there's nothing, but I was just trying to test it to see what would happen.

**Comment by jcollins-g** [comment] 2021-06-11 16:24
I can not reproduce the problem.  Using 2.13.1 and 0.42.0 dartdoc, we correctly generate docs for https://gitea.com/Cutewarriorlover/lumos at commit 2a6510ea866f9446e3400a1a873b06b19834d532

Could you give more details on the execution environment for dartdoc?  What command line flags were used, the current working directory, etc?

**Comment by Cutewarriorlover** [comment] 2021-06-11 17:12
My cwd was `/home/leo/lumos`, with no command line flags (so just `dartdoc`).

**Comment by jcollins-g** [comment] 2021-06-11 17:14
@Cutewarriorlover It looks from the exception like the .packages or .dart_tool directory might be corrupted for some reason.  Could you remove those and any pubspec.lock that exists and retry?

**Comment by ykdosto** [comment] 2021-06-14 13:04
use: `flutter pub global run dartdoc:dartdoc`

**Comment by Cutewarriorlover** [comment] 2021-06-16 18:07
> @Cutewarriorlover It looks from the exception like the .packages or .dart_tool directory might be corrupted for some reason. Could you remove those and any pubspec.lock that exists and retry?

That didn't work.

**Comment by jcollins-g** [comment] 2021-08-19 18:53
Given that I can't reproduce the bug I'm going to close this for now as it looks like a damaged installation.

**Closed by jcollins-g** 2021-08-19 18:53 UTC
Labels: needs info
