### ISSUE TITLE
"Comment reference resolution inside extension methods is not yet implemented"

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#2526] opened 2021-02-18 22:55 UTC
I think this is a blocker for my PR where I introduce an extension type, since I am unable to document it. Is there some workaround I can apply?

**Comment by jcollins-g** [comment] 2021-02-19 16:14
There is no workaround.    Closing, this is a duplicate of #2033.

**Closed by jcollins-g** 2021-02-19 16:14 UTC
