### ISSUE TITLE
Wrong doc comments for methods with missing return type

### ISSUE THREAD

**Issue by d2m** [dart-lang/dartdoc#568] opened 2015-06-10 05:52 UTC
E.g. 
```
/// A class
class Klass {
  /// A method
  method() {
  }

  /// Another method
  another() {
  }

  /// A shadowed method
  toString() {    
  }
}
```

becomes 
```
Instance Methods

  method
  () → dynamic
  A method
  
  another
  () → dynamic
  A method

  toString
  () → dynamic
  Another method
```

**Comment by sethladd** [comment] 2015-06-10 06:10
Thanks for the report. What's weird is that I also saw this once. Digging
in it looks like it was a bug in the analyzer. I couldn't repro it
conclusively. Does this case repro for you and what version of dart doc and
analyzer are you using?

On Wednesday, June 10, 2015, Michael Haubenwallner <notifications@github.com>
wrote:

> E.g.
>
> /// A class
> class Klass {
>   /// An instance property
>   String property;
>
>   /// A constructor
>   Klass();
>
>   /// A method
>   method() {
>   }
>
>   /// Another method
>   another() {
>   }
>
>   /// A shadowed method
>   toString() {
>   }
>
> becomes
>
> Instance Methods
>
>   method
>   () → dynamic
>   A method
>
>   another
>   () → dynamic
>   A method
>
>   toString
>   () → dynamic
>   Another method
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dartdoc/issues/568>.
>


-- 
Sent from my Motorola Startac

**Comment by d2m** [comment] 2015-06-10 06:21
It is reproducible for me. Dartdoc is the current master from github.
dartdoc version: 0.0.2+2
analyzer is 0.25.0+1
Dart VM version: 1.10.0 (Fri Apr 24 03:54:01 2015) on "linux_ia32"

Do you want me to try with the latest Dart dev release?

**Comment by sethladd** [comment] 2015-06-10 07:02
Excellent, thanks for verifying. This is a real thing, then. We'll need to dig in.

**Comment by sethladd** [comment] 2015-06-10 07:03
@keertip @devoncarew  this is probably a bug with analyzer, at least that's what it seemed on my initial investigation.

(See https://groups.google.com/a/dartlang.org/forum/#!topic/analyzer-discuss/pHOwEY6f_Wc)

What's a good way to proceed?

**Comment by keertip** [comment] 2015-06-10 14:15
Will see if I can reproduce this with a test case for the analyzer team. If it is a bug in the analyzer, it should be fixed.

**Comment by sethladd** [comment] 2015-06-10 15:18
Thanks for taking a look! If I can help, let me know.

**Comment by a14n** [comment] 2015-06-10 15:39
maybe related to dart-lang/sdk#23523

**Comment by keertip** [comment] 2015-06-10 20:24
This is an analyzer bug which has been fixed. Tested with the `analyzer 0.25.1-alpha.1` and dartdoc generates with the right comments.

**Closed** 2015-06-10 21:27 UTC
Labels: bug, P0

**Comment by sethladd** [comment] 2015-06-11 06:45
woohoo, thanks for tracking this down!
