### ISSUE TITLE
Duplicated Library Entries

### ISSUE THREAD

**Issue by Coconutter** [dart-lang/dartdoc#897] opened 2015-09-10 13:53 UTC
For no apparent reason, dartdoc adds one of my libraries **always** twice to the index file.
Parsing part is ok - file only parsed ones, but generating part shows that same file is picked up twice, see file "ESPFields.dart" in img. This is a permanent issue - re-running dartdoc does not change the output.
* Only one doc/api/espfields/ folder is created
* I have only one lib/ root with all files within
* Its always the same file causing the issue

File dart content is very simple:

```dart
/// # [JAVA-Rooted!] JSON fields, used by all sinks.
library espfields;
import 'EPFields.dart';
class ESPFields extends EPFields {
static const String MODE = 'mode';
static const String CMD = 'cmd';
static const String WAITTIME = 'wt';
static const String IVAL = 'ival';
static const String REP = 'rep';
static const String DVCS = 'dvcs';
static const String STATUS = 'status';
}
```
![libtwice](https://cloud.githubusercontent.com/assets/14218501/9789774/5fc1c7d8-57d2-11e5-8835-c301bd4744ec.png)

**Comment by keertip** [comment] 2015-09-10 15:07
How can I reproduce this problem? Is the library you are generating docs for public?

**Comment by sethladd** [comment] 2015-09-18 20:31
Thanks for the report! We can't reproduce it locally. If you can provide us with an example project that demonstrates the issue, that would be really helpful.

**Comment by sethladd** [comment] 2015-09-28 17:23
Closing because we don't know how to reproduce. Please do reopen this if you have an example for us to test. Thanks!

**Closed by sethladd** 2015-09-28 17:23 UTC
Labels: needs_info
