### ISSUE TITLE
Analyzer issue in dartdoc? Old version?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/dartdoc#1252] opened 2016-09-26 15:37 UTC
I'm seeing [build failures](https://www.dartdocs.org/documentation/code_builder/0.1.3/log.txt) on what should be valid Dart code for [code_builder](https://github.com/dart-lang/code_builder/blob/master/lib/dart/core.dart). 

The error(s):

```
[error] Invalid constant value at lib/dart/core.dart, line 18.
[error] 'const' variables must be constant value at lib/dart/core.dart, line 18.
[error] Expected an identifier at lib/dart/core.dart, line 18.
[error] Arguments of a constant creation must be constant expressions at lib/dart/core.dart, line 18.
```

Code in question:

``` dart
const AnnotationBuilder atOverride = const AnnotationBuilder.reference(
  'override',
  'dart:core',
);
```

My only guess is that the version of the analyzer is too old, and it doesn't understand trailing commas. If that's the case, can we get a bump and re-publish to the website?

**Comment by keertip** [comment] 2016-09-26 15:39
Yes, looks like it. Could you confirm if you using the version of dartdoc published on pub.dartlang?

**Comment by matanlurey** [comment] 2016-09-26 18:46
This is just a build error from pub.dartlang (I've never invoked manually)

**Comment by matanlurey** [comment] 2016-10-01 14:58
Ping :)

**Comment by devoncarew** [comment] 2016-10-01 18:20
It looks like dartdoc.org is running dart doc from the version published on pub. It should be using the dart doc shipped as part of the sdk. That way we can ensure that it's up to date with the latest analyzer and language changes.

**Comment by sethladd** [comment] 2016-10-01 18:23
Should we publish a newer version of Dart doc to pub?

**Comment by matanlurey** [comment] 2016-10-05 21:41
Ping :) Just want to see this assigned to someone with an approximate ETA, otherwise I don't have a lot of motivation to write dartdoc if it will just crash building. I'll even do it if someone can give me a pointer.

**Comment by keertip** [comment] 2016-10-05 22:11
Looking into it now, will have an update shortly.

**Comment by keertip** [comment] 2016-10-05 22:21
Opened an [issue](https://github.com/astashov/dartdocs.org/issues/31) for Anton to update the dartdoc being used.

Now looking at fixing dartdoc on pub.dartlang

**Comment by matanlurey** [comment] 2016-10-05 22:24
Thanks!

**Comment by sethladd** [comment] 2016-10-05 22:24
Thanks Keerti!

**Comment by keertip** [comment] 2016-10-06 20:04
It turns out that code_builder requires sdk 1.19, while dartdocs.org is still using 1.18. Opened an [issue](https://github.com/astashov/dartdocs.org/issues/32) for that.

Also opened an [issue](https://github.com/dart-lang/dartdoc/issues/1254) to update the crossdart linking code in dartdoc for changes to the analyzer.

**Comment by keertip** [comment] 2016-10-06 21:01
Closing this as we now have issues tracking the root causes.

**Comment by matanlurey** [comment] 2016-11-16 00:31
https://www.dartdocs.org/documentation/code_builder/0.1.3/ :-/

**Comment by devoncarew** [comment] 2016-11-16 00:46
I see the build failures here: https://www.dartdocs.org/documentation/code_builder/0.1.3/log.txt

And a lot of messages about constants:

```
Invalid constant value at lib/dart/core.dart, line 96.
```

perhaps a duplicate of https://github.com/dart-lang/sdk/issues/27829?

**Closed** 2016-11-22 07:05 UTC
