### ISSUE TITLE
Dartdoc crashes on url_launcher 2.0.2

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#1627] opened 2018-03-06 09:17 UTC
```
dartdoc --version
dartdoc version: 0.17.0
```

```
git clone https://github.com/flutter/plugins
cd plugins/packages/url_launcher
flutter packages get
dartdoc
```

```
Generation failed: NoSuchMethodError: The getter 'library' was called on null.
Receiver: null
Tried calling: library
dart:core                                                                               Object.noSuchMethod
package:dartdoc/src/element_type.dart 176                                               ElementType._getElementTypeFrom
package:dartdoc/src/element_type.dart 135                                               ElementType.typeArguments.<fn>
dart:_internal                                                                          ListIterable.toList
package:dartdoc/src/element_type.dart 136                                               ElementType.typeArguments
package:dartdoc/src/element_type.dart 57                                                ElementType.linkedName
package:dartdoc/src/element_type.dart 166                                               ElementType.createLinkedReturnTypeName
package:dartdoc/src/model.dart 3679                                                     ModelFunctionTyped.linkedReturnType
dart:mirrors                                                                            _LocalInstanceMirror.getField
package:mustache4dart/src/mirrors.dart 111                                              _MethodMirrorField.val
package:mustache4dart/mustache_context.dart 122                                         _MustacheContext._getMustacheContext
package:mustache4dart/mustache_context.dart 118                                         _MustacheContext._getContextForKey
package:mustache4dart/mustache_context.dart 82                                          _MustacheContext._getInThisOrParent
package:mustache4dart/mustache_context.dart 78                                          _MustacheContext.field
package:mustache4dart/src/tokens.dart 169                                               _ExpressionToken.apply
package:mustache4dart/src/tokens.dart 40                                                Token.call
package:mustache4dart/src/tmpl.dart 101                                                 _Template._write
package:mustache4dart/src/tmpl.dart 76                                                  _Template.call
package:mustache4dart/src/mustache.dart 11                                              render
package:mustache4dart/src/tokens.dart 211                                               _PartialToken.apply
package:mustache4dart/src/tokens.dart 286                                               _StartSectionToken.apply.<fn>.<fn>
package:mustache4dart/src/tokens.dart 309                                               _StartSectionToken.forEachUntilEndSection
package:mustache4dart/src/tokens.dart 286                                               _StartSectionToken.apply.<fn>
dart:core                                                                               Iterable.forEach
package:mustache4dart/src/tokens.dart 285                                               _StartSectionToken.apply
package:mustache4dart/src/tokens.dart 299                                               _StartSectionToken.apply.<fn>
package:mustache4dart/src/tokens.dart 309                                               _StartSectionToken.forEachUntilEndSection
package:mustache4dart/src/tokens.dart 299                                               _StartSectionToken.apply
package:mustache4dart/src/tokens.dart 40                                                Token.call
package:mustache4dart/src/tmpl.dart 101                                                 _Template._write
package:mustache4dart/src/tmpl.dart 76                                                  _Template.call
package:dartdoc/src/html/html_generator_instance.dart 280                               HtmlGeneratorInstance._build
package:dartdoc/src/html/html_generator_instance.dart 180                               HtmlGeneratorInstance.generateLibrary
package:dartdoc/src/html/html_generator_instance.dart 93                                HtmlGeneratorInstance._generateDocs
package:dartdoc/src/html/html_generator_instance.dart 36                                HtmlGeneratorInstance.generate
===== asynchronous gap ===========================
dart:async                                                                              _Completer.completeError
package:dartdoc/src/html/html_generator_instance.dart                                   HtmlGeneratorInstance.generate
===== asynchronous gap ===========================
dart:async                                                                              new Future.microtask
package:dartdoc/src/html/html_generator_instance.dart 34                                HtmlGeneratorInstance.generate
package:dartdoc/src/html/html_generator.dart 106                                        HtmlGenerator.generate
===== asynchronous gap ===========================
dart:async                                                                              new Future.microtask
package:dartdoc/src/html/html_generator.dart 72                                         HtmlGenerator.generate
package:dartdoc/dartdoc.dart 171                                                        DartDoc.generateDocs
===== asynchronous gap ===========================
dart:async                                                                              _asyncThenWrapperHelper
package:dartdoc/dartdoc.dart 157                                                        DartDoc.generateDocs
/b/build/slave/dart-sdk-mac-dev/build/sdk/third_party/pkg/dartdoc/bin/dartdoc.dart 274  main.<fn>.<fn>
===== asynchronous gap ===========================
dart:async                                                                              new Future.microtask
/b/build/slave/dart-sdk-mac-dev/build/sdk/third_party/pkg/dartdoc/bin/dartdoc.dart 273  main.<fn>.<fn>
dart:async                                                                              runZoned
/b/build/slave/dart-sdk-mac-dev/build/sdk/third_party/pkg/dartdoc/bin/dartdoc.dart 273  main.<fn>
===== asynchronous gap ===========================
dart:async                                                                              new Future.microtask
/b/build/slave/dart-sdk-mac-dev/build/sdk/third_party/pkg/dartdoc/bin/dartdoc.dart 272  main.<fn>
package:stack_trace                                                                     Chain.capture
/b/build/slave/dart-sdk-mac-dev/build/sdk/third_party/pkg/dartdoc/bin/dartdoc.dart 272  main
```

**Comment by jcollins-g** [comment] 2018-03-06 15:36
duplicate of #1625

**Closed by jcollins-g** 2018-03-06 15:36 UTC

**Comment by jcollins-g** [comment] 2018-03-13 19:30
Publish of [0.17.1](https://github.com/dart-lang/dartdoc/releases/tag/v0.17.1%2B1) should enable you to build docs for this package now; it worked for me when I tried at least.  Please let me know if you have further issues.
