### ISSUE TITLE
Links on front page are broken

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/dartdoc#844] opened 2015-08-21 12:10 UTC
The three links to "fundamental APIs" right at the top of the new SDK front page are broken: Clicking them leads to an all empty page.

Concretely, here:
https://new-dartdocs-dot-dartlang-api.appspot.com/1.12.0-dev.5.8/index.html
the links to dart:core, dart:html, and dart:io are broken.

**Comment by sethladd** [comment] 2015-08-21 15:01
Dupe of https://github.com/dart-lang/dartdoc/issues/829

Thanks for the report!

**Closed by sethladd** 2015-08-21 15:01 UTC
