### ISSUE TITLE
dartdoc is failing on several flutter packages

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/dartdoc#1560] opened 2017-12-06 10:52 UTC
Seeing several failures for Flutter packages on dartdocs.org:
https://www.dartdocs.org/history/index.html

For example:
https://www.dartdocs.org/documentation/chewie/0.2.0/log.txt
https://www.dartdocs.org/documentation/flutter_launcher_icons/0.0.3/log.txt
https://www.dartdocs.org/documentation/flutter_tools/0.0.1/log.txt

**Comment by mit-mit** [comment] 2017-12-06 10:52
cc @jcollins-g

**Comment by jcollins-g** [comment] 2017-12-06 17:01
This looks like dartdocs.org doesn't have the Flutter SDK configured.

**Comment by devoncarew** [comment] 2017-12-06 17:23
Not sure those are all current. I'm not sure why `flutter_tools` was published; it's at `0.0.1` in that failure log. I don't see a date to hand for it, and it's not listed in https://pub.dartlang.org/packages/flutter_tools.

**Comment by devoncarew** [comment] 2017-12-06 17:23
(`chewie` would be current however)

**Comment by jcollins-g** [comment] 2017-12-06 17:30
The flutter errors were red herrings as crossdart apparently just doesn't work on Flutter.  The dartdoc error is a duplicate of #1543 and will be fixed when 0.15.0 is published.

**Closed by jcollins-g** 2017-12-06 17:30 UTC
Labels: customer flutter
