### ISSUE TITLE
Add an Edit link to every generated page

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#1892] opened 2019-01-09 00:46 UTC
It would be great if every generated page of dartdocs could link to the relevant line on GitHub so that someone could really easily edit the docs and submit a PR for proposed changes.

P2 (Enhancements considered important but without significant data indicating they are a big win)

(From https://github.com/flutter/flutter/issues/10416)

**Comment by jcollins-g** [comment] 2019-01-25 23:32
This is largely a duplicate of #1454.   I now have an implementation on deck good enough for Flutter's use (at least for Flutter-owned packages).  The implementation will be able to link to an arbitrary URL constructed via a template and controlled via flags or dartdoc_options.yaml.  From dartdoc's --help:

```
    --link-to-repository-excludes                 A list of directories to exclude from linking to a source code repository.
    --link-to-repository-revision                 Revision number to insert into the URI.
    --link-to-repository-root                     Path to a local directory that is the root of the repository we link to.  All source code files under this directory will be linked.
    --link-to-repository-uri-template             Substitute into this template to generate a uri for an element's source code.
                                                               Dartdoc dynamically substitutes the following fields into the template:
                                                                 %f%:  Relative path of file to the repository root
                                                                 %r%:  Revision number
                                                                 %l%:  Line number

```

...and will have that link visible on all element pages next to the title.

![screenshot from 2019-01-25 15-22-47](https://user-images.githubusercontent.com/14116827/51778222-68be9280-20b5-11e9-94c7-a31e4ee8ed17.png)

The text `<source code>` will be replaced with an icon; checking with @kwalrath on what would be good for us to use there.  Because the link is arbitrary, it could go to github's edit link as @Hixie suggest's, or simply view the source as requested in #1454.

**Closed** 2019-02-01 18:22 UTC
Labels: P2, customer flutter, enhancement
