### ISSUE TITLE
Can't generate Angular docs on Travis: dartdoc seems to hang

### ISSUE THREAD

**Issue by chalin** [dart-lang/dartdoc#1743] opened 2018-08-20 19:38 UTC
Attempting to generate Angular 5.0.0 API docs for [PR 1792](https://github.com/dart-lang/site-webdev/pull/1792), dartdoc seems to hang once it reaches `angular_test`, as shown by [this Travis (Linux) log](https://travis-ci.org/dart-lang/site-webdev/jobs/417407741) -- the corresponding build times out after 10 min.

```console
> dart --version
Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "linux_x64"
> pub global run dartdoc --version
dartdoc version: 0.20.3
```

I have no issues generating the docs under MacOS.

cc @kwalrath @kevmoo

**Comment by chalin** [comment] 2018-08-21 15:41
Hmm, or maybe it is failing over ACX? This is the end of [another Travis log](https://travis-ci.org/dart-lang/site-webdev/jobs/417407741): notice the "waiting for 1 threads..."

```
...
parsing lib/laminate/popup/module.dart...

parsing lib/laminate/popup/popup.dart...

Attempt:11 waiting for 1 threads to check in
```

**Comment by chalin** [comment] 2018-08-21 22:04
Hmm, the problem seems to have [gone away](https://travis-ci.org/dart-lang/site-webdev/jobs/418810597).

**Comment by chalin** [comment] 2018-09-20 18:39
The problem is back: Travis terminates jobs because dartdoc fails to produce any output after 10 min. E.g.:

- https://travis-ci.org/dart-lang/site-webdev/jobs/431133402
- https://travis-ci.org/dart-lang/site-webdev/jobs/430614993
- https://travis-ci.org/dart-lang/site-webdev/jobs/430666897

**Comment by chalin** [comment] 2018-09-21 19:10
FYI, with https://travis-ci.org/dart-lang/site-webdev/jobs/431557183, I'm seeing the same error from earlier:

```
Attempt:11 waiting for 1 threads to check in
Attempt:12 waiting for 1 threads to check in
```

**Comment by jcollins-g** [comment] 2018-09-21 20:17
I am having some difficulties with Travis but can not reproduce them -- sometimes Dartdoc travis jobs fail to terminate as well.

**Comment by kwalrath** [comment] 2018-09-26 21:09
It looks like the build is working again, as of today...

**Comment by jcollins-g** [comment] 2018-09-28 20:32
And dartdoc's own travis seems not to be hanging randomly anymore, either.  Closing again for now.

**Closed** 2018-10-01 18:39 UTC
Labels: P1, bug

**Comment by chalin** [comment] 2018-10-24 11:17
Dartdoc is hanging again https://travis-ci.org/dart-lang/site-webdev/jobs/445373602:

```
EXEC start: pub global run dartdoc --include=angular_test {"cwd":"tmp/pub-packages/angular_test-2.1.0"}
Generating documentation for 'angular' into /home/travis/build/dart-lang/site-webdev/tmp/pub-packages/angular-5.1.0/doc/api/
Generating documentation for 'angular_router' into /home/travis/build/dart-lang/site-webdev/tmp/pub-packages/angular_router-2.0.0-alpha+20/doc/api/
Generating documentation for 'angular_components' into /home/travis/build/dart-lang/site-webdev/tmp/pub-packages/angular_components-0.10.0/doc/api/
Generating documentation for 'angular_forms' into /home/travis/build/dart-lang/site-webdev/tmp/pub-packages/angular_forms-2.1.0/doc/api/
Generating documentation for 'angular_test' into /home/travis/build/dart-lang/site-webdev/tmp/pub-packages/angular_test-2.1.0/doc/api/
Resolving dependencies...
+ analyzer 0.33.0
[snip]
+ yaml 2.1.15
Downloading json_annotation 2.0.0...
Changed 41 dependencies!
Precompiling executables...
Precompiled csslib:css.
parsing lib/builder.dart...
parsing lib/security.dart...
parsing lib/angular.dart...
parsing lib/core.dart...
parsing lib/di.dart...
parsing lib/meta.dart...
parsing lib/experimental.dart...
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by jcollins-g** [comment] 2018-10-24 17:59
@chalin If your travis runs are hanging with dartdoc, it may be necessary to implement the Travis workaround from #1769.  Try adding that and see if your hanging problems go away.
