### ISSUE TITLE
navigating through search results goes out of order

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#3222] opened 2022-10-14 17:34 UTC
STEPS TO REPRODUCE
1. Go to https://master-api.flutter.dev/
2. Press tab twice to focus the search bar.
3. Type "FileSystem". The top four results are "Press Enter to see all results", the dart:html class, the package:file class, and the FileSystemEntity class in package:file.
4. Tap the down arrow key three times to get to the FileSystemEntity class.

EXPECTED RESULTS
Each result gets highlighted in turn, each tap moving the highlight down by one.

ACTUAL RESULTS
It highlights the fifth result, skipping over the fourth. If you tap down enough times the focus jumps around the list and eventually highlights the fourth result.

**Comment by srawlins** [comment] 2022-10-17 01:15
Duplicate of https://github.com/dart-lang/dartdoc/issues/3204

**Closed by srawlins** 2022-10-17 01:15 UTC
