### ISSUE TITLE
flutter docs are missing lots of classes

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#1236] opened 2016-08-29 19:00 UTC
The 0.9.7+2 release introduced an issue where the generated docs for flutter are missing many classes.

This page: https://docs.flutter.io/flutter/material/material-library.html

only shows ~5 classes.

**Comment by devoncarew** [comment] 2016-08-29 20:03
https://github.com/flutter/flutter/pull/5644

**Comment by sethladd** [comment] 2016-09-19 22:41
Is this still the case?

**Comment by Hixie** [comment] 2016-10-18 16:46
Moving to P0 because if this isn't fixed then it's going to block deployment of subsequent fixes.

**Comment by eseidelGoogle** [comment] 2016-11-21 17:40
Correct, we're intentionally pinned on an older version of dartdoc due to this regression:
https://github.com/flutter/flutter/blob/master/dev/bots/docs.sh#L5

**Comment by astashov** [comment] 2016-12-13 06:15
It seems like the bug is in analyzer. It got broken at [this commit](https://github.com/dart-lang/dartdoc/commit/8a1da1f63ba4c464cf9d802f8182e8be9c9fae78), when the analyzer version was bumped to ^0.28.1 (and it's still broken with 0.29.1). If I just change the analyzer version back to 0.27 at that commit and nothing else, it works just fine and generates all the classes successfully.

It seems like that happens because by some reason doesn't gather exported namespaces correctly. E.g., there: https://github.com/dart-lang/dartdoc/blob/648ad06319d1ff46927b025d6f9088c7957257c7/lib/src/model.dart#L973, analyzer 0.27 returns the namespace instance with like 600+ records inside, and analyzer 0.28 returns the namespace with just ~10 records.

@devoncarew do you want me to dig it deeper, or you will pass this to the analyzer team?

**Comment by keertip** [comment] 2016-12-13 06:21
@bwilkerson , should dartdoc be doing something else instead of 
```
_exportedNamespace =
        new NamespaceBuilder().createExportNamespaceForLibrary(element);
```

to get all the public elements for a library? Has this api changed?

**Comment by bwilkerson** [comment] 2016-12-13 17:01
No, the API hasn't changed, and the code hasn't changed since 6/16, and most of it has been stable since 4/16. I don't see any obvious cause for the issue. I'll need to get a reproduction case so that I can step through the creation of the namespace.

**Comment by keertip** [comment] 2016-12-13 18:50
@astashov , how did you run dartdoc on flutter?

**Comment by eseidelGoogle** [comment] 2016-12-13 18:51
https://github.com/flutter/flutter/blob/master/dev/bots/docs.sh will generate all of Flutter's docs.

**Comment by astashov** [comment] 2016-12-13 19:04
To use a debugger, I run it somewhat like this:

```
git clone https://github.com/flutter/flutter.git ~/projects/flutter
cd ~/projects/flutter
bin/flutter update-packages
git clone https://github.com/dart-lang/dartdoc.git ~/projects/dartdoc
cd ~/projects/dartdoc
pub get

DART_SDK=~/projects/flutter/bin/cache/dart-sdk FLUTTER_ROOT=~/projects/flutter bin/dartdoc.dart \
  --header ~/projects/flutter/dev/docs/styles.html \
  --header ~/projects/flutter/dev/docs/analytics.html \
  --exclude temp_doc \
  --favicon=~/projects/flutter/dev/docs/favicon.ico \
  --use-categories \
  --include-external animation \
  --include-external cassowary \
  --include-external foundation  \
  --include-external gestures \
  --include-external http \
  --include-external material \
  --include-external painting \
  --include-external physics \
  --include-external rendering \
  --include-external scheduler \
  --include-external services \
  --include-external widgets \
  --include-external driver_extension \
  --include-external flutter_driver \
  --include-external flutter_markdown \
  --include-external flutter_markdown_raw \
  --include-external flutter_test \
  --input ~/projects/flutter/dev/docs \
  --output ~/projects/flutter/dev/docs/doc/api
```

I can try to provide [SSCCE](http://sscce.org/) for it, if you want.

**Comment by keertip** [comment] 2016-12-14 03:47
Found the problem - dartdoc is picking up the wrong library named `material`. It is  generating docs for `flutter/lib/src/material/material.dart` instead of `flutter/lib/material.dart`. Working on making the `--include-external` flag more strict. Once that is in place, can tweak the flutter docs script to pass in more unambiguous names for the libraries.

**Comment by eseidelGoogle** [comment] 2016-12-14 04:10
Fantastic! Thank you both!

**Comment by astashov** [comment] 2016-12-14 04:13
@keertip woohoo, great job! I'll move on to https://github.com/dart-lang/dartdoc/issues/1153 then :)

**Comment by eseidelGoogle** [comment] 2016-12-14 04:16
Should library name collisions have caused (or cause in the future) some sort of warning inside dartdoc or the analyzer?  We're happy to update names and/or be more specific for flags like --include-external as necessary in Flutter.

**Comment by sethladd** [comment] 2016-12-14 05:26
Yay!

And printing out a warning sounds like a good idea.

**Closed** 2016-12-14 17:30 UTC
Labels: customer flutter, P0

**Comment by sethladd** [comment] 2016-12-14 17:31
Thanks @keertip ! Do we need to do anything on the Flutter side?

**Comment by eseidelGoogle** [comment] 2016-12-14 19:49
Now that @keertip and @astashov did the hard work of figuring out what was wrong. :)  I decided to slap together an alternative fix which includes the warnings I had imagined:
https://github.com/eseidelGoogle/dartdoc/tree/external_warnings

If that's useful to either @devoncarew or @keertip, please feel free to take it!  (Note that in that commit it's using the old match function instead of @keertip's new one, the new one is included commented out.)

Note that running with that patch I immediately see more potential problems with the current system (even after the fix):
```
ERROR: animation matches multiple libraries: (/src/flutter/packages/flutter/lib/animation.dart, /src/flutter/packages/flutter/lib/src/animation/animation.dart)
ERROR: http matches multiple libraries: (/src/flutter/packages/flutter/lib/src/http/http.dart, /src/flutter/packages/flutter/lib/http.dart)
ERROR: material matches multiple libraries: (/src/flutter/packages/flutter/lib/src/material/material.dart, /src/flutter/packages/flutter/lib/material.dart)
WARNING: driver_extension matches no libraries.
```

**Comment by devoncarew** [comment] 2016-12-14 20:57
Thanks Eric! The additional checks make sense; better to fast-fail here if there's ambiguity about the library to gen docs for.
