### ISSUE TITLE
Flutter builds broken for a while on travis...

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dartdoc#1490] opened 2017-08-31 03:08 UTC
https://travis-ci.org/dart-lang/dartdoc/jobs/270198958

Wondering if this is due to the current Dart SDK Flutter is synced to.

![screen shot 2017-08-30 at 8 08 31 pm](https://user-images.githubusercontent.com/17034/29904729-0769b04e-8dbf-11e7-92ee-44fd553d4759.png)

**Comment by devoncarew** [comment] 2017-08-31 14:44
This is a dupe of https://github.com/dart-lang/dartdoc/issues/1478.

**Closed by devoncarew** 2017-08-31 14:44 UTC
Labels: P1
