### ISSUE TITLE
Click to copy-paste constant names

### ISSUE THREAD

**Issue by jmagman** [dart-lang/dartdoc#2933] opened 2022-02-03 19:41 UTC
Request the ability to tap somewhere on a constant name to copy to clipboard.  Example given is for icon names.

https://api.flutter.dev/flutter/cupertino/CupertinoIcons-class.html
https://api.flutter.dev/flutter/material/Icons-class.html

> We've (@bdlukaa and @henry2man) just implemented a new Icon Gallery for **FluentUI toolkit** (https://pub.dev/packages/fluent_ui), you can see it in action:
> 
> 1. Go to https://bdlukaa.github.io/fluent_ui/
> 2. On the side menu, press "Icons"
> 
> <img width="1246" alt="Captura de pantalla 2022-02-03 a las 11 38 05" src="https://user-images.githubusercontent.com/4610108/152326789-4afbc6a2-b4ef-4b9f-9905-6c0202691da1.png">
> ...
> Also please take notice of the _click-n-copy-to-clipboard™️_ feature that we've just implemented in FluentUI Icon Gallery (all icons are `Buttons`, every button press copies the full name of the icon into the [clipboard](https://pub.dev/packages/clipboard) ).

_Originally posted by @henry2man in https://github.com/flutter/flutter/issues/88754#issuecomment-1028847737_

**Comment by srawlins** [comment] 2022-03-25 20:03
Love the idea. Duplicate of https://github.com/dart-lang/dartdoc/issues/1737.

**Closed by srawlins** 2022-03-25 20:03 UTC
Labels: enhancement, P2
