### ISSUE TITLE
Bump markdown to 0.9.0

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dartdoc#968] opened 2015-10-17 18:16 UTC
There are a few features new in the markdown package, [version 0.9.0](https://github.com/dart-lang/markdown/blob/master/CHANGELOG.md). Some of the docs in the SDK already assumed they were here: ([HttpRequest.statusText](https://api.dartlang.org/1.12.1/dart-html/HttpRequest/statusText.html) tries to escape things with backslashes, [ByteData.getInt16](https://api.dartlang.org/133511/dart-typed_data/ByteData/getInt16.html) tries to use inline HTML).

However, there are some incompatibilities that should be addressed before dartdoc bumps markdown to 0.9.0:
- [ ] Backslashes will need to be escaped, like in [Uri.file](https://api.dartlang.org/133511/dart-core/Uri/Uri.file.html), Uri.toFilePath, FilesystemEntity.
- [ ] Inline HTML that was assumed to be escaped will need to be actually escaped now, like in [AreaElement](https://api.dartlang.org/1.12.1/dart-html/AreaElement-class.html).
- [ ] Inline "HTML" that is actually Dart generics, like in [RandomAccessFile.readIntoSync](https://api.dartlang.org/133511/dart-io/RandomAccessFile/readIntoSync.html)
- [x] dart-lang/sdk#23601 needs to be fixed. Two patches mailed.
- [x] #966 needs to be fixed.

**Comment by keertip** [comment] 2016-07-21 18:23
Done! dartdoc is at 0.10.1 now.

**Comment by srawlins** [comment] 2016-07-21 18:35
Were the incompatibilities above addressed? I did a fair amount of research to find those problems, so it shouldn't be hard to fix the SDK code, if it hasn't been fixed yet.

**Comment by keertip** [comment] 2016-07-21 18:43
Not confirmed. We went ahead and updated markdown to get other fixes that dartdoc needed. Thanks for pointing this out, will keep this open so that we can check and open issues if sdk docs need to be changed.

**Comment by srawlins** [comment] 2016-07-21 18:50
They should be pretty easy to fix. Until they are, some docs will just be a little wonky, especially things like [`Uri.file()`](https://api.dartlang.org/stable/1.17.1/dart-core/Uri/Uri.file.html), which has a careful discussion of backslashes, which will render wrong:

* Pre Markdown 0.9: `\\` renders as `\\`.
* Markdown 0.9 and later: `\\` renders as `\`.

**Comment by devoncarew** [comment] 2016-07-22 19:05
@srawlins, some fixes out for review here: https://codereview.chromium.org/2180473002/. I didn't see the issues in AreaElement, so perhaps they've since been addressed.

**Comment by devoncarew** [comment] 2016-11-14 19:06
Closing this - we're at markdown `0.11.1` now. If there are issues with the existing sdk docs, those should be opened against the sdk repo. Thanks!

**Closed by devoncarew** 2016-11-14 19:06 UTC
