### ISSUE TITLE
Blank line after {@endtemplate} is dropped

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#2171] opened 2020-04-02 22:05 UTC
Consider this source:
```
  /// Clip further painting using a rectangle.
  ///
  /// {@template flutter.rendering.object.needsCompositing}
  /// The `needsCompositing` argument specifies whether the child needs
  /// compositing. Typically this matches the value of
  /// [RenderObject.needsCompositing] for the caller. If false, this method
  /// returns null, indicating that a layer is no longer necessary. If a render
  /// object calling this method stores the `oldLayer` in its
  /// [RenderObject.layer] field, it should set that field to null.
  ///
  /// When `needsCompositing` is false, this method will use a more efficient
  /// way to apply the layer effect than actually creating a layer.
  /// {@endtemplate}
  ///
  /// {@template flutter.rendering.object.pushClipLayer.offset}
  /// The `offset` argument is the offset from the origin of the canvas'
  /// coordinate system to the origin of the caller's coordinate system.
  /// {@endtemplate}
  ///
  /// The `clipRect` is the rectangle (in the caller's coordinate system) to use
  /// to clip the painting done by [painter]. It should not include the
  /// `offset`.
```
It generates this output:
> Clip further painting using a rectangle.
>
> The needsCompositing argument specifies whether the child needs compositing. Typically this matches the value of RenderObject.needsCompositing for the caller. If false, this method returns null, indicating that a layer is no longer necessary. If a render object calling this method stores the oldLayer in its RenderObject.layer field, it should set that field to null.
>
> When needsCompositing is false, this method will use a more efficient way to apply the layer effect than actually creating a layer. The offset argument is the offset from the origin of the canvas' coordinate system to the origin of the caller's coordinate system. The clipRect is the rectangle (in the caller's coordinate system) to use to clip the painting done by painter. It should not include the offset.

Observe how "actually creating a layer. The offset argument" does not have a newline and how "coordinate system. The clipRect is" also does not have a newline. In both cases the paragraph breaks are lost.

Source (approximate): 
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/object.dart#L403

Output:
https://master-api.flutter.dev/flutter/rendering/PaintingContext/pushClipRect.html

**Comment by Hixie** [comment] 2020-04-02 22:05
cc @gspencergoog @jcollins-g

**Comment by srawlins** [comment] 2020-09-06 03:11
Duplicate of #1848

**Closed by srawlins** 2020-09-06 03:11 UTC
Labels: P2, bug, customer flutter
