### ISSUE TITLE
 Invalid argument(s): join(null, "bin", "cache", "dart-sdk"): part 0 was null, but part 1 was not.

### ISSUE THREAD

**Issue by rajat-girnar** [dart-lang/dartdoc#2279] opened 2020-07-31 09:48 UTC
while we generating doc this error will come.And I set dart-SDK path ,flutter-SDK path but is not working

**Comment by srawlins** [comment] 2020-07-31 13:14
Thanks for filing this issue! Would you mind sharing the command you used to run dartdoc? I guess I'm mostly interested in seeing the Dart SDK path and Flutter SDK path.

**Comment by rajat-girnar** [comment] 2020-08-06 10:40
Command for Dartdoc : **dartdoc**
Dart-Sdk Path :  **export PATH=/home/rajat/Documents/sdk/flutter/bin/cache/dart-sdk/bin/:$PATH**
Flutter-SDK Path:  **export PATH=/home/rajat/Documents/sdk/flutter/bin/:$PATH** 
@srawlins  please check this

**Comment by Quwaysim** [comment] 2020-08-14 08:57
I'm having the same issue

**Comment by sakebook** [comment] 2020-08-24 18:12
I tried this and it solved the problem.

https://github.com/dart-lang/dartdoc/issues/1705

**Comment by sidrao2006** [comment] 2020-08-27 03:18
Duplicate of #1705

**Closed** 2020-08-27 22:55 UTC
Labels: needs info
