### ISSUE TITLE
Dartdoc fails after console VM snapshot of html_dart2js.dart instead of html_dart2js.dart 

### ISSUE THREAD

**Issue by terrylucas** [dart-lang/dartdoc#1492] opened 2017-08-31 19:53 UTC
Snapshot of html_dart2js.dart in the console VM instead of html_dartium.dart has introduced a bug in dartdoc.

Janice tracked it down to https://github.com/dart-lang/dartdoc/blob/master/lib/src/model.dart#L2335    a.element is unexpectedly allowed to be NULL in the analyzer.

Needs to be fixed by release 1.25.0-dev.16.0 (next Tue/Wed 9/5-9/6).

**Comment by jcollins-g** [comment] 2017-08-31 19:55
duplicate of #1491

**Closed by jcollins-g** 2017-08-31 19:55 UTC
Labels: P1
